name=NeuStorage
version=1.0.0
author=Ulywae (@neufa) <ulywae@gmail.com>
maintainer=Ulywae (@neufa) <ulywae@gmail.com>
sentence=A lightweight, fast, and powerful NVS wrapper for ESP32 without String overhead.
paragraph=NeuStorage is designed for high-performance ESP32 applications. It uses C++ templates to store any trivially copyable data (like structs, ints, and floats) directly as binary blobs, ensuring zero dynamic memory allocation and no memory fragmentation.
category=Data Storage
url=https://github.com/ulywae/NeuStorage
architectures=esp32
includes=NeuStorage.h
